import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/src/app/providers/theme-provider'
import { Header } from '@/src/widgets'
import Link from 'next/link'
import { Web3Provider } from '@/src/app/providers/web3-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative flex h-screen flex-col">
            <Header />
            <main className="container mx-auto max-w-7xl flex-grow px-6 pt-16">
              <Web3Provider>{children}</Web3Provider>
            </main>
            <footer className="flex w-full items-center justify-center py-3">
              <Link
                className="flex items-center gap-1 text-current"
                href="https://heroui.com?utm_source=next-app-template"
                title="heroui.com homepage"
              >
                <span className="text-default-600">Powered by</span>
                <p className="text-primary">HeroUI</p>
              </Link>
            </footer>
          </div>
        </ThemeProvider>
        <div id="background-radial-gradient" />
      </body>
    </html>
  )
}
